apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  labels:
    app: todo-app
spec:
  replicas: 1            # increase for more pods (requires shared DB)
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: piyushc04/todo-flask-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: todo-app-config
            optional: false
# Uncomment below to persist the SQLite file with a PVC.
#This is not recommended for production SO im not doing it.
        # volumeMounts:
        # - name: sqlite-storage
        #   mountPath: /app/todo.db
      # volumes:
      # - name: sqlite-storage
      #   persistentVolumeClaim:
      #     claimName: todo-sqlite-pvc
