apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  labels:
    app: todo-app
spec:
  type: NodePort            # Use ClusterIP for ingress‑based access
  selector:
    app: todo-app
  ports:
    - port: 5000            # Service port inside the cluster
      targetPort: 5000      # Container port
      nodePort: 30007       # Exposed port on each node
